name: drop_contrastive_loss
_target_: model.losses.SoftContrastiveLoss

margin: ${model.margin}
max_violation: ${model.max_violation}
threshold_homo: ${model.threshold_homo}
threshold_hetero: ${model.threshold_hetero}
