name: server

device: cuda

# specific attributes to this machine
# Size of a training mini-batch.
batch_size: 32

num_workers: 8
# Number of training epochs.
num_epochs: 60
# Initial learning rate.
learning_rate: 0.0002
# Gradient clipping threshold.
grad_clip: 0
# Number of epochs to update the learning rate.
lr_update: 30

# Number of steps to print and record the log.
log_step: 10

# Number of steps to run validation.
val_step: 500

warm_up: ${model.warm_up}

dataname: ${data.dataname}
